{% set name = "pyromark" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyromark-{{ version }}.tar.gz
  sha256: 7cd0d5b83fa51d74c5256a446113210be3609fe83fc8d5bd394950cfa6983b2f

build:
  skip: true  # [py<39]
  entry_points:
    - pyromark = pyromark._cli:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python
    - typing_extensions >=3.7.4.2

test:
  imports:
    - pyromark
  commands:
    - pip check
    - pyromark --help
  requires:
    - pip

about:
  home: https://github.com/monosans/pyromark
  doc_url: https://pyromark.readthedocs.io/
  summary: Blazingly fast Markdown parser for Python written in Rust.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
