{% set name = "pyromark" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyromark-{{ version }}.tar.gz
  sha256: bccc573d6a9a656da3131d842f5e2a3c913b71740e22f05774922ed81d48c2bd

build:
  skip: true  # [py<39]
  entry_points:
    - pyromark = pyromark.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python
    - typing_extensions >=3.7.4.2

test:
  imports:
    - pyromark
  commands:
    - pip check
    - pyromark --help
  requires:
    - pip

about:
  home: https://github.com/monosans/pyromark
  doc_url: https://pyromark.readthedocs.io/
  summary: Blazingly fast Markdown parser for Python written in Rust.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
