{% set name = "pyromark" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyromark-{{ version }}.tar.gz
  sha256: b814fe1f8e52da783099e53f2a5df07d2a3e80e417af23f3aa923d939458fdb4

build:
  skip: True  # [py<37]
  entry_points:
    - pyromark = pyromark.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python

test:
  imports:
    - pyromark
  commands:
    - pip check
    - pyromark --help
  requires:
    - pip

about:
  home: https://github.com/monosans/pyromark
  doc_url: https://pyromark.readthedocs.io/
  summary: Blazingly fast Markdown parser for Python written in Rust.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
